mail:
  host: smtp.gmail.com
  port: 587
  username: bookloredev@gmail.com
  password: "hihr arui ycke gtvh"
  from: "bookloredev@gmail.com"
  auth: true
  starttls: true

spring:
  application:
    name: TrackLore
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/Workspace/Tracklore/data/tracklore-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true